matrix_info:
  module: modules.matrix_info.matrix_info
  class: MatrixInfo
  MatrixInfo:
    in_adapter_mode: '''in_bat3d_cam60'''

label:
  module: abstract.stage
  class: Stage
  Stage:
    in_adapter_mode: '''in_scale_ai_adapter'''
    out_adapter_mode: '''out_yolotianxiaomo_adapter'''
    adapter_config_path: '''modules/label/adapter.yaml'''
